#!/bin/sh
touch ./game/dashBoard.html
touch ./game/gameInfo.html
touch ./game/gameStatus.html
touch ./game/gameFinished.html
touch ./game/gameCategoryInfo.html
touch ./game/gameBonusConfig.html
touch ./cache/moneyDeposit.html
touch ./cache/moneyWithdraw.html
touch ./cache/moneyDividend.html
touch ./cache/moneyPurchase.html
touch ./cache/moneyPayment.html
touch ./cache/moneyPayback.html
touch ./cache/moneyAdminPoint.html
touch ./user/userInfo.html
touch ./user/userBettingUser.html
touch ./user/userBlackList.html
touch ./user/gameUserBettingStatus.html
touch ./user/gameHQUserBettingStatus.html
touch ./user/userHQUser.html
touch ./user/userAgency.html
touch ./user/userBranch.html
touch ./user/userLeft.html
touch ./user/userJoinApprove.html
touch ./statistics/statisticsInfo.html
touch ./statistics/statisticsAggrBettingByTerm.html
touch ./statistics/statisticsAggrBettingByUser.html
touch ./statistics/statisticsAggrMoneyByTerm.html
touch ./statistics/statisticsAggrMoneyByUser.html
touch ./statistics/statisticsMoneyByTerm.html
touch ./statistics/statisticsSettle.html
touch ./community/communityBoards.html
touch ./community/communityBoardNotice.html
touch ./community/communityEvents.html
touch ./community/communityEventNotice.html
touch ./community/communityCs.html
touch ./community/communityCsNotice.html
touch ./community/communityBoardManage.html
touch ./manage/manageSettings.html
touch ./manage/manageNoticeManage.html
touch ./manage/manageIpBlock.html
touch ./manage/manageAdminIp.html


touch ./game/dashBoard.js
touch ./game/gameInfo.js
touch ./game/gameStatus.js
touch ./game/gameFinished.js
touch ./game/gameCategoryInfo.js
touch ./game/gameBonusConfig.js
touch ./game/gameUserBettingStatus.js
touch ./game/gameHQUserBettingStatus.js
touch ./cache/moneyDeposit.js
touch ./cache/moneyWithdraw.js
touch ./cache/moneyDividend.js
touch ./cache/moneyPurchase.js
touch ./cache/moneyPayment.js
touch ./cache/moneyPayback.js
touch ./cache/moneyAdminPoint.js
touch ./user/userInfo.js
touch ./user/userBettingUser.js
touch ./user/userBlackList.js
touch ./user/userHQUser.js
touch ./user/userAgency.js
touch ./user/userBranch.js
touch ./user/userLeft.js
touch ./user/userJoinApprove.js
touch ./statistics/statisticsInfo.js
touch ./statistics/statisticsAggrBettingByTerm.js
touch ./statistics/statisticsAggrBettingByUser.js
touch ./statistics/statisticsAggrMoneyByTerm.js
touch ./statistics/statisticsAggrMoneyByUser.js
touch ./statistics/statisticsMoneyByTerm.js
touch ./statistics/statisticsSettle.js
touch ./community/communityBoards.js
touch ./community/communityBoardNotice.js
touch ./community/communityEvents.js
touch ./community/communityEventNotice.js
touch ./community/communityCs.js
touch ./community/communityCsNotice.js
touch ./community/communityBoardManage.js
touch ./manage/manageSettings.js
touch ./manage/manageNoticeManage.js
touch ./manage/manageIpBlock.js
touch ./manage/manageAdminIp.js