#!/bin/sh
touch ./game/dashBoard.html
touch ./game/gameInfo.html
touch ./game/gameStatus.html
touch ./game/gameClosed.html
touch ./game/gameCate.html
touch ./game/bounsConfig.html
touch ./cache/charge.html
touch ./cache/change.html
touch ./cache/dividend.html
touch ./cache/purchase.html
touch ./cache/payment.html
touch ./cache/payback.html
touch ./cache/adminPoint.html
touch ./user/userInfo.html
touch ./user/bettingUser.html
touch ./user/blackList.html
touch ./user/userBattingStatus.html
touch ./user/HQUserBattingStatus.html
touch ./user/HQUser.html
touch ./user/agency.html
touch ./user/branch.html
touch ./user/withdrawal.html
touch ./user/underLine.html
touch ./statistics/statistics.html
touch ./statistics/aggrBettingByTerm.html
touch ./statistics/aggrBettingByUser.html
touch ./statistics/aggrMoneyByTerm.html
touch ./statistics/aggrMoneyByUser.html
touch ./statistics/moneyByTerm.html
touch ./statistics/statement .html
touch ./community/boards.html
touch ./community/boardNotice.html
touch ./community/events.html
touch ./community/eventNotice.html
touch ./community/cs.html
touch ./community/csNotice.html
touch ./community/boardManage.html
touch ./etc/company.html
touch ./etc/noticeManage.html
touch ./etc/ipBlock.html
touch ./etc/adminIp.html


touch ./game/dashBoard.js
touch ./game/gameInfo.js
touch ./game/gameStatus.js
touch ./game/gameClosed.js
touch ./game/gameCate.js
touch ./game/bounsConfig.js
touch ./cache/charge.js
touch ./cache/change.js
touch ./cache/dividend.js
touch ./cache/purchase.js
touch ./cache/payment.js
touch ./cache/payback.js
touch ./cache/adminPoint.js
touch ./user/userInfo.js
touch ./user/bettingUser.js
touch ./user/blackList.js
touch ./user/userBattingStatus.js
touch ./user/HQUserBattingStatus.js
touch ./user/HQUser.js
touch ./user/agency.js
touch ./user/branch.js
touch ./user/withdrawal.js
touch ./user/underLine.js
touch ./statistics/statistics.js
touch ./statistics/aggrBettingByTerm.js
touch ./statistics/aggrBettingByUser.js
touch ./statistics/aggrMoneyByTerm.js
touch ./statistics/aggrMoneyByUser.js
touch ./statistics/moneyByTerm.js
touch ./statistics/statement .js
touch ./community/boards.js
touch ./community/boardNotice.js
touch ./community/events.js
touch ./community/eventNotice.js
touch ./community/cs.js
touch ./community/csNotice.js
touch ./community/boardManage.js
touch ./etc/company.js
touch ./etc/noticeManage.js
touch ./etc/ipBlock.js
touch ./etc/adminIp.js